# Generated by Django 3.0 on 2023-03-14 05:43

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.CharField(auto_created=True, default=judge.models.uid, editable=False, max_length=128, primary_key=True, serialize=False, verbose_name='赛事ID')),
                ('OrganizerID', models.CharField(max_length=128, verbose_name='组织者ID')),
                ('organizers_mobile', models.CharField(max_length=11)),
                ('organizers_email', models.CharField(max_length=50)),
                ('organizers_unit', models.CharField(max_length=128)),
                ('flag', models.BooleanField(default=False)),
                ('race_name', models.CharField(max_length=128)),
                ('race_time', models.CharField(max_length=128)),
                ('race_file', models.FileField(blank=True, null=True, upload_to='judge/appendix/')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(default=judge.models.uid, editable=False, max_length=128, verbose_name='赛事ID')),
                ('Cptr_id', models.CharField(default=judge.models.uid, editable=False, max_length=128, verbose_name='选手ID')),
                ('Cptr_Name', models.CharField(max_length=128, verbose_name='选手姓名')),
                ('Cptr_gender', models.CharField(default='男', max_length=128, verbose_name='性别')),
                ('Cptr_phone', models.CharField(default=None, max_length=11)),
                ('Cptr_email', models.CharField(default=None, max_length=50)),
                ('Cptr_unit', models.CharField(default=None, max_length=128)),
                ('video_upload_date', models.DateTimeField(default=None, verbose_name='上传日期')),
                ('video_path', models.FileField(upload_to='judge/video/', verbose_name='视频url')),
                ('img_path', models.ImageField(default=None, upload_to='judge/video/picture/', verbose_name='图片url')),
                ('HumanScore', models.TextField(default=None, null=True)),
                ('VoiceScore', models.TextField(default=None, null=True)),
                ('PoseScore', models.TextField(default=None, null=True)),
            ],
            options={
                'unique_together': {('race_id', 'Cptr_id')},
            },
        ),
    ]
