# Generated by Django 3.0 on 2023-03-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_file',
            field=models.CharField(default=123, max_length=1280),
            preserve_default=False,
        ),
    ]
