# Generated by Django 3.2.18 on 2023-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20230314_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
