# Generated by Django 3.2.15 on 2023-03-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='bytes_recv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='bytes_send',
            field=models.IntegerField(default=0),
        ),
    ]
