# Generated by Django 3.2.15 on 2023-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20230311_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='timestamp',
            field=models.FloatField(default=0),
        ),
    ]
