# Generated by Django 3.2.15 on 2023-03-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_visit_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='timestamp',
            new_name='time_stamp',
        ),
    ]
