# Generated by Django 3.2.15 on 2023-03-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_rename_timestamp_visit_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='bytes_sent',
        ),
    ]
