# Generated by Django 3.2.15 on 2023-03-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_visit_bytes_sent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visit',
            table=None,
        ),
    ]
