# Generated by Django 3.0 on 2023-02-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Black_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('prohibit_time', models.DateTimeField(max_length=32)),
                ('access_time', models.DateTimeField(max_length=32)),
                ('prohibit_span', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='defend_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('time', models.DateTimeField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('rule', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=64)),
                ('address', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ip_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16, unique=True)),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.SmallIntegerField(choices=[(1, 'Black'), (0, 'White'), (2, 'Temporary')], default=1)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='pass_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('time', models.DateTimeField(max_length=32)),
                ('path', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=128)),
                ('headers', models.CharField(max_length=256)),
            ],
        ),
    ]
