# Generated by Django 3.2.15 on 2023-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_list',
            name='prohibit_span',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
