# Generated by Django 3.0 on 2023-04-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_log',
            name='headers',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='pass_log',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
