# Generated by Django 3.0 on 2023-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0002_auto_20230315_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defend_log',
            name='path',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pass_log',
            name='path',
            field=models.CharField(max_length=128),
        ),
    ]
