# Generated by Django 3.2.18 on 2023-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0002_alter_black_list_prohibit_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defend_log',
            name='path',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pass_log',
            name='path',
            field=models.CharField(max_length=256),
        ),
    ]
