# Generated by Django 3.2.15 on 2023-03-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0003_pass_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_list',
            name='description',
            field=models.CharField(default='暂无', max_length=64),
        ),
        migrations.AlterField(
            model_name='ip_list',
            name='frequency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ip_list',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Black'), (0, 'White'), (2, 'Temporary'), (3, 'None')], default=3),
        ),
    ]
