# Generated by Django 3.2.15 on 2023-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0004_auto_20230312_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_list',
            name='prohibit_span',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ip_list',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Black'), (0, 'White'), (2, 'Temporary'), (3, 'None')]),
        ),
    ]
