# Generated by Django 3.2.15 on 2023-03-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0005_auto_20230312_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defend_log',
            name='rule',
            field=models.CharField(max_length=64),
        ),
    ]
