# Generated by Django 3.2.15 on 2023-03-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0006_alter_defend_log_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='admin', max_length=30)),
                ('password', models.CharField(default='admin', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='defend_log',
            name='rule',
            field=models.CharField(max_length=32),
        ),
    ]
