# Generated by Django 3.2.15 on 2023-03-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0007_auto_20230324_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='admin',
        ),
    ]
