# Generated by Django 3.2.15 on 2023-03-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0008_rename_user_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='waf_admin',
        ),
    ]
