# Generated by Django 3.2.18 on 2023-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoofWaf', '0009_rename_admin_waf_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defend_log',
            name='path',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pass_log',
            name='path',
            field=models.CharField(max_length=256),
        ),
    ]
