# Generated by Django 3.2 on 2022-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_time', models.DateTimeField(max_length=20, verbose_name='演讲时间')),
                ('content', models.TextField(max_length=16370, verbose_name='内容')),
                ('fluency_score', models.FloatField(max_length=10, verbose_name='流畅度')),
                ('integrity_score', models.FloatField(max_length=10, verbose_name='完整度')),
                ('phone_score', models.FloatField(max_length=10, verbose_name='声调')),
                ('tone_score', models.FloatField(max_length=10, verbose_name='音调')),
                ('topic_score', models.FloatField(max_length=10, null=True, verbose_name='主旨契合度')),
                ('affix_score', models.FloatField(max_length=10, null=True, verbose_name='缀词扣分')),
                ('total_score', models.FloatField(max_length=10, null=True, verbose_name='总得分')),
                ('body_score', models.FloatField(max_length=10, null=True, verbose_name='肢体动作得分')),
            ],
        ),
    ]
