# Generated by Django 3.0 on 2023-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0002_auto_20230216_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_score',
            fields=[
                ('create_timw', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
