# Generated by Django 3.0 on 2023-03-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0003_text_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text_score',
            old_name='create_timw',
            new_name='create_time',
        ),
    ]
