# Generated by Django 3.0 on 2023-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0004_auto_20230308_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_score',
            name='text',
            field=models.TextField(max_length=16370, verbose_name='内容'),
        ),
    ]
