# Generated by Django 3.2.18 on 2023-05-02 16:10

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.CharField(auto_created=True, default=login.models.uid, editable=False, max_length=128, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(default='default.png', upload_to='avatar', verbose_name='头像')),
                ('status_flag', models.CharField(default='0', max_length=1)),
            ],
            options={
                'verbose_name': '用户表',
                'ordering': ['registration_time'],
            },
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(auto_created=True, editable=False, max_length=128, verbose_name='用户ID')),
                ('date', models.DateTimeField(default=None, verbose_name='开始日期')),
                ('img', models.ImageField(max_length=256, upload_to='', verbose_name='图片')),
                ('imgTime', models.CharField(default='', max_length=128, verbose_name='图片时间')),
                ('emotion', models.CharField(max_length=64, verbose_name='表情')),
                ('pose', models.ImageField(max_length=256, upload_to='', verbose_name='姿态')),
                ('score', models.FloatField(default=-1.0, verbose_name='评分')),
                ('flag', models.BooleanField(default=False, verbose_name='是否变化')),
                ('limbsChanges', models.IntegerField(default=0, verbose_name='四肢变化')),
                ('bodyDeviation', models.IntegerField(default=0, verbose_name='人体偏移')),
            ],
        ),
        migrations.CreateModel(
            name='Speach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(auto_created=True, editable=False, max_length=128, verbose_name='用户ID')),
                ('date', models.DateTimeField(max_length=20, verbose_name='演讲时间')),
                ('total_score', models.FloatField(max_length=10, verbose_name='总得分')),
                ('content', models.CharField(max_length=10000, verbose_name='内容')),
                ('color_content', models.CharField(default=None, max_length=10000, verbose_name='演讲准确度文本')),
                ('fluency_score', models.FloatField(max_length=10, verbose_name='流畅度')),
                ('integrity_score', models.FloatField(max_length=10, verbose_name='完整度')),
                ('phone_score', models.FloatField(max_length=10, verbose_name='声调')),
                ('tone_score', models.FloatField(max_length=10, verbose_name='音调')),
                ('affix_score', models.FloatField(max_length=10, verbose_name='缀词扣分')),
                ('topic_score', models.FloatField(default=None, max_length=10, null=True, verbose_name='主旨契合度')),
                ('video_path', models.ImageField(default=None, max_length=256, upload_to='', verbose_name='视频路径')),
            ],
        ),
    ]
