# Generated by Django 3.2.18 on 2023-04-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pose',
            name='flag',
        ),
        migrations.AddField(
            model_name='pose',
            name='bodyDeviation',
            field=models.IntegerField(default=0, verbose_name='人体偏移'),
        ),
        migrations.AddField(
            model_name='pose',
            name='limbsChanges',
            field=models.IntegerField(default=0, verbose_name='人体变化'),
        ),
    ]
