# Generated by Django 3.2.18 on 2023-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230420_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='是否变化'),
        ),
        migrations.AlterField(
            model_name='pose',
            name='limbsChanges',
            field=models.IntegerField(default=0, verbose_name='四肢变化'),
        ),
    ]
